apiVersion: v1
items:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    creationTimestamp: null
    generation: 1
    labels:
      app: olapic-app-nodejs
      project: content-engine-admin-localbox
      service: nodejs
      vendor: Olapic
    name: nodejs-content-engine-admin
  spec:
    replicas: 1
    selector:
      context: nodejs-content-engine-admin-context
      name: nodejs-content-engine-admin
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 1
        maxUnavailable: 1
        timeoutSeconds: 120
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        creationTimestamp: null
        labels:
          context: nodejs-content-engine-admin-context
          name: nodejs-content-engine-admin
      spec:
        containers:
        - name: nodejs-content-engine-admin
          env:
            - name: 'PORT'
              value: '8080'
            - name: 'APP_TITLE'
              value: ''
            - name: 'APP_HTML_TITLE'
              value: 'Olapic (Local)'
            - name: 'SSO_URL'
              value: "https://sso.local.photorank.me"
            - name: 'ADMIN_API_2_URL'
              value: "http://php-admin-api-v2.olapic.svc:8080"
            - name: 'API_V2_URL'
              value: "http://php-apiv2.olapic.svc:8080"
            - name: 'AUTHNZ_API_URL'
              value: "http://php-eiam-authnz-server.olapic.svc:8080"
            - name: 'CONTENT_PUBLISHING_URL'
              value: "https://publish.photorank.me"
            - name: 'DOWNLOADER_ALLOWED_DOMAINS'
              value: "https://s3.amazonaws.com,https://videos.olapic-cdn.com"
            - name: 'EMAIL_STUDIO_URL'
              value: "https://emailstudio.photorank.me"
            - name: 'DEBUG_CONFIGURATION_CONTROLLER'
              value: "true"
            - name: 'DEBUG_LOG_REQUESTS'
              value: "true"
            - name: 'DEBUG_SHOW_ERRORS'
              value: "true"
            - name: 'IMAGE_SERVER_URL'
              value: "https://s3.amazonaws.com/photorank-media/media"
            - name: 'LEMURAMA_ANALYTICS_URL'
              value: "https://localhost:8002/index.html#"
            - name: 'MOE_URL'
              value: "https://moe.local.photorank.me"
            - name: 'PERMISSIONS_URL'
              value: "https://permissions.local.photorank.me"
            - name: 'PHOTORANK_URL'
              value: "https://local.photorank.me"
            - name: 'PINTEREST_GATEWAY_API_URL'
              value: "https://pinterest-gateway.local.photorank.me"
            - name: 'REPORTING_API_URL'
              value: "https://reporting.local.photorank.me"
            - name: 'SANDBOX_URL'
              value: "https://sandbox.local.photorank.me"
            - name: 'SCHEDULER_API_URL'
              value: "https://task-scheduler.local.photorank.me"
            - name: 'SHARING_API_URL'
              value: "https://sharing.photorank.me/v1"
            - name: 'SOCIAL_CONNECTOR_API_URL'
              value: "https://socialconnector.local.photorank.me"
            - name: 'TAPSHOP_ADMIN_URL'
              value: "https://tapshop-admin.local.photorank.me"
            - name: 'UPLOADER_API_URL'
              value: "https://uploader.photorank.me/v1"
            - name: 'UPLOADER_PREVIEWER_API_URL'
              value: "https://uploaderv3previewer.photorank.me"
            - name: 'GA_ENABLED'
              value: "false"
            - name: 'FS_ENABLED'
              value: "false"
            - name: 'HEAP_ENABLED'
              value: "false"
            - name: 'INTERCOM_ENABLED'
              value: "false"
            - name: 'SENTRY_ENABLED'
              value: "false"
          image: nodejs-content-engine-admin:latest
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 8080
            protocol: TCP
          resources:
            limits:
              cpu: 300m
              memory: 100M
            requests:
              cpu: 50m
              memory: 25M
          securityContext:
            capabilities: {}
            privileged: false
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        - name: nodejs-content-engine-admin-test
          env:
            - name: 'PORT'
              value: '8081'
            - name: 'APP_TITLE'
              value: ''
            - name: 'APP_HTML_TITLE'
              value: 'Olapic (Local Test)'
            - name: 'SSO_URL'
              value: "https://sso.local.photorank.me"
            - name: 'ADMIN_API_2_URL'
              value: "http://php-admin-api-v2:8081"
            - name: 'API_V2_URL'
              value: "http://php-apiv2.svc:8081"
            - name: 'AUTHNZ_API_URL'
              value: "http://php-eiam-authnz-server.svc:8081"
            - name: 'CONTENT_PUBLISHING_URL'
              value: "https://publish.photorank.me"
            - name: 'DOWNLOADER_ALLOWED_DOMAINS'
              value: "https://s3.amazonaws.com,https://videos.olapic-cdn.com"
            - name: 'EMAIL_STUDIO_URL'
              value: "https://emailstudio.photorank.me"
            - name: 'DEBUG_CONFIGURATION_CONTROLLER'
              value: "true"
            - name: 'DEBUG_LOG_REQUESTS'
              value: "true"
            - name: 'DEBUG_SHOW_ERRORS'
              value: "true"
            - name: 'IMAGE_SERVER_URL'
              value: "https://s3.amazonaws.com/photorank-media/media"
            - name: 'LEMURAMA_ANALYTICS_URL'
              value: "https://localhost:8002/index.html#"
            - name: 'MOE_URL'
              value: "https://moe.local.photorank.me"
            - name: 'PERMISSIONS_URL'
              value: "https://permissions.local.photorank.me"
            - name: 'PHOTORANK_URL'
              value: "https://local.photorank.me"
            - name: 'PINTEREST_GATEWAY_API_URL'
              value: "https://pinterest-gateway.local.photorank.me"
            - name: 'REPORTING_API_URL'
              value: "https://microcks.comoros.photorank.me/rest/Sirius/1.0.0"
            - name: 'SANDBOX_URL'
              value: "https://sandbox.local.photorank.me"
            - name: 'SCHEDULER_API_URL'
              value: "https://task-scheduler.local.photorank.me"
            - name: 'SHARING_API_URL'
              value: "https://sharing.photorank.me/v1"
            - name: 'SOCIAL_CONNECTOR_API_URL'
              value: "https://socialconnector.local.photorank.me"
            - name: 'TAPSHOP_ADMIN_URL'
              value: "https://tapshop-admin.local.photorank.me"
            - name: 'UPLOADER_API_URL'
              value: "https://uploader.photorank.me/v1"
            - name: 'UPLOADER_PREVIEWER_API_URL'
              value: "https://uploaderv3previewer.photorank.me"
            - name: 'GA_ENABLED'
              value: "false"
            - name: 'FS_ENABLED'
              value: "false"
            - name: 'HEAP_ENABLED'
              value: "false"
            - name: 'INTERCOM_ENABLED'
              value: "false"
            - name: 'SENTRY_ENABLED'
              value: "false"
          image: nodejs-content-engine-admin:automation
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 8081
            protocol: TCP
          resources:
            limits:
              cpu: 300m
              memory: 100M
            requests:
              cpu: 50m
              memory: 25M
          securityContext:
            capabilities: {}
            privileged: false
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
    test: false
    triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
        - nodejs-content-engine-admin
        from:
          kind: ImageStreamTag
          name: nodejs-content-engine-admin:latest
          namespace: olapic
      type: ImageChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - nodejs-content-engine-admin-test
        from:
          kind: ImageStreamTag
          name: nodejs-content-engine-admin:automation
          namespace: olapic
      type: ImageChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - nginx-content-engine-admin
        from:
          kind: ImageStreamTag
          name: nginx-localbox:4
          namespace: olapic
      type: ImageChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - nginx-content-engine-admin-test
        from:
          kind: ImageStreamTag
          name: nginx-localbox:4
          namespace: olapic
      type: ImageChange
    - type: ConfigChange
- apiVersion: v1
  kind: "ImageStream"
  apiVersion: "v1"
  metadata:
    name: "nodejs-content-engine-admin"
  spec:
    dockerImageRepository: 740906069008.dkr.ecr.us-east-1.amazonaws.com/service/content-engine-admin
    tags:
      -
        name: 'automation'
        from:
          kind: DockerImage
          name: '740906069008.dkr.ecr.us-east-1.amazonaws.com/service/content-engine-admin:automation'
        importPolicy:
          scheduled: true
      -
        name: 'latest'
        from:
          kind: DockerImage
          name: '740906069008.dkr.ecr.us-east-1.amazonaws.com/service/content-engine-admin:latest'
        importPolicy:
          scheduled: true
- apiVersion: v1
  kind: Route
  metadata:
    creationTimestamp: null
    labels:
      app: olapic-app-nodejs
      project: content-engine-admin-localbox
      service: nodejs
      vendor: Olapic
    name: nodejs-content-engine-admin-route
  spec:
    host: admin.local.photorank.me
    port:
      targetPort: nodejs-content-engine-admin-endpoint
    tls:
      certificate: |-
        -----BEGIN CERTIFICATE-----
        MIIEVTCCAz2gAwIBAgIJAIGfWk5yu9ruMA0GCSqGSIb3DQEBBQUAMIGJMQswCQYD
        VQQGEwJVUzERMA8GA1UECAwITmV3IFlvcmsxETAPBgNVBAcMCE5ldyBZb3JrMRMw
        EQYDVQQKDApPbGFwaWMgSU5DMR0wGwYDVQQDDBQqLmxvY2FsLnBob3RvcmFuay5t
        ZTEgMB4GCSqGSIb3DQEJARYRZGV2b3BzQG9sYXBpYy5jb20wHhcNMTUwMjA1MTcz
        MTExWhcNMjUwMjAyMTczMTExWjCBiTELMAkGA1UEBhMCVVMxETAPBgNVBAgMCE5l
        dyBZb3JrMREwDwYDVQQHDAhOZXcgWW9yazETMBEGA1UECgwKT2xhcGljIElOQzEd
        MBsGA1UEAwwUKi5sb2NhbC5waG90b3JhbmsubWUxIDAeBgkqhkiG9w0BCQEWEWRl
        dm9wc0BvbGFwaWMuY29tMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA
        vL0RwEgRtHLC9A+JsTCN53ASwKmURB8u4Sw2D5qpFq9PXOrcY17XKIc3O+3Yjx78
        ecGfQ6JhuL0No3SsRWyrjz27IXP+otjASmUhSeSx3cIRtrlCFZnp0uXo26Pqxr1R
        FxjsxA6AezxLWq3MFHq59401rBD/l+pE8Yg2XfwIeSP20YqUclGMRYi54iOF21tk
        6QcME5kvf0e+BIwieW2uDTo8vexcbJw+UpQUjmzIhtATobMxAMgObWKSeY8BqVyH
        cP3brMzuXIVkveh7pg9UeBUqQfAy5IDkxSGDnSC+cYTdDEXW27bPJevgOXBbs7vP
        JM79MfGqwjQ+pgzY95ZNVwIDAQABo4G9MIG6MB0GA1UdDgQWBBTzLPi28mqyWsFK
        Fcof8E3Xiu7uiTAfBgNVHSMEGDAWgBTzLPi28mqyWsFKFcof8E3Xiu7uiTAMBgNV
        HRMEBTADAQH/MAsGA1UdDwQEAwIFoDBdBgNVHREEVjBUghJsb2NhbC5waG90b3Jh
        bmsubWWCFHdpZGdldHMucGhvdG9yYW5rLm1lghJkZWJ1Zy5waG90b3JhbmsubWWC
        FCoubG9jYWwucGhvdG9yYW5rLm1lMA0GCSqGSIb3DQEBBQUAA4IBAQBJkaR4zeSF
        KAokvtYuGS175sOoNj4zkcCTYzYV9AuX1GWj0qBoPk2t/m31g9DreO2CsOXNVcBT
        YFR+L+gAiSCX5VGgPfqb7TsfOpR2brHZL+Wh/HkZ4Y9vt0/196eMqFp7saPe/V65
        J9RBIU1CVnacINRaHokMX/1Qif88AtPg8gO+MOt47udSoD80ub7wtQlpMTCCzHK1
        gHodoC9ljZ5XVQzWlD+t6kuX4NjRotgBiYfAAu4Us3XeAyfPkQxoQNlixOi8LAby
        UCFU4i0vih7bJOqZL7fJxuHDw+hPXG2j/0lkKzmjuvw9JXtREssze/BD5DsaXe02
        bkhNTDqthPON
        -----END CERTIFICATE-----
      insecureEdgeTerminationPolicy: Redirect
      key: |-
        -----BEGIN RSA PRIVATE KEY-----
        MIIEpAIBAAKCAQEAvL0RwEgRtHLC9A+JsTCN53ASwKmURB8u4Sw2D5qpFq9PXOrc
        Y17XKIc3O+3Yjx78ecGfQ6JhuL0No3SsRWyrjz27IXP+otjASmUhSeSx3cIRtrlC
        FZnp0uXo26Pqxr1RFxjsxA6AezxLWq3MFHq59401rBD/l+pE8Yg2XfwIeSP20YqU
        clGMRYi54iOF21tk6QcME5kvf0e+BIwieW2uDTo8vexcbJw+UpQUjmzIhtATobMx
        AMgObWKSeY8BqVyHcP3brMzuXIVkveh7pg9UeBUqQfAy5IDkxSGDnSC+cYTdDEXW
        27bPJevgOXBbs7vPJM79MfGqwjQ+pgzY95ZNVwIDAQABAoIBAQCefb78UwjbGUvx
        G2MrMnTXltuIgl8JXY5GdJPpQp0feZQRmP/9SlUvqWyOnMqwVPr7W8bcSu347nkX
        fBB2NC1VGiecjgWUxqOjVY1AuhVK/X9Wi/ecoCUkfwCuANZUkgIYfUvFz8/ArP8y
        ZKPtxqmH4kLh/VxFO+stUI8nGVAcOM+3Rqc746RG+4mq8ff0t5mkSwKfMKxBcbO+
        U1nlsCjzWTg74yiCE5xPPD7jozC44gGO5czd54QaMVvl2hsj71V8YP8HLbaf+/mE
        OXIhaU5jn0/DSrsUeFJdVV1eLXd9rVGhgifdk5W2AB7waqrdZ+5BqPNOl8Z59wcg
        71F7SesxAoGBAOVcsmzAemJonIUbl8yfIYuqpit1a+XXX9ow5T0goezNT85Keuos
        BHfK6Si7UXyDChWEZUbELR22EX3Fj+RU/0TlYMpnypeLsXx61e2Led/yXbx8owLO
        AYg5bupqCI4QM70nHH5rvfb3uxUXGzb6Y+aiUE3yZul/njSzosNNla9jAoGBANKo
        kbeT3s9ilanYt4dgHs1YXnHqoC/BPS/OmFqOB4Q9m5QKZIWpouaHja4ifd04jqK9
        /p+r/goY0XdvDwvsPTZvCm5Ufulo7N7WOAvAMfdXcW7uSiv9I665RERRa2PqUssJ
        Ge7H1dk+MXC7Jq02hCDq9Nng1DfqheIXcuu9is59AoGBAJF9r6DUp81s1nyI+E3Q
        U5Mo+KdwoLT3XdImWgPgg1aXFhyhmj6ZFWx3xlcUG6iD5w2nIic1ofjK2WWSwKfy
        Usr9Rdye4iAneLqhoLpCU1j/gP5jgXPyAX7MD9Oa1zpmhKtj9+sppSLYGlBSi+zg
        ACb4p0AKl8VeMpjzqjeBK4ZJAoGAIVlMUDqZkE00EkJbs5O07J8rvG7/UvANhq73
        EYbgi7/RDFuk1EApqMMW29VcBZR5iCv5zj9FJUYOixDK2gFZI2/qv9KikMLqlNBm
        6P1RK63tKDmTBmm5p2Ru+T3GeXfUCY50S4fZQ94Dp6wJEGzL+AYaIw/jqMJ41XUO
        3WERQ2UCgYAZWObD+BxHlKBc2Q+KSDwG587BqL+tFnGwT91uJbGXBo/TgbW1Oftw
        f3eeGZ2PrX9ovzq9WvXzOdkVohaQuBQTi0hE167KXbxuFGAPiMKCDc1JspPVK6/8
        c/JGPaZUPEUKI0fqYDD1baxjqSc/9kzzRRs/JTXid8rMr2uSze4Zjw==
        -----END RSA PRIVATE KEY-----
      termination: edge
    to:
      kind: Service
      name: nodejs-content-engine-admin
      weight: 100
    wildcardPolicy: None
- apiVersion: v1
  kind: Route
  metadata:
    creationTimestamp: null
    labels:
      app: olapic-app-nodejs
      project: content-engine-admin-localbox
      service: nodejs
      vendor: Olapic
    name: nodejs-content-engine-admin-test-route
  spec:
    host: admin-test.local.photorank.me
    port:
      targetPort: nodejs-content-engine-admin-test-endpoint
    tls:
      certificate: |-
        -----BEGIN CERTIFICATE-----
        MIIEVTCCAz2gAwIBAgIJAIGfWk5yu9ruMA0GCSqGSIb3DQEBBQUAMIGJMQswCQYD
        VQQGEwJVUzERMA8GA1UECAwITmV3IFlvcmsxETAPBgNVBAcMCE5ldyBZb3JrMRMw
        EQYDVQQKDApPbGFwaWMgSU5DMR0wGwYDVQQDDBQqLmxvY2FsLnBob3RvcmFuay5t
        ZTEgMB4GCSqGSIb3DQEJARYRZGV2b3BzQG9sYXBpYy5jb20wHhcNMTUwMjA1MTcz
        MTExWhcNMjUwMjAyMTczMTExWjCBiTELMAkGA1UEBhMCVVMxETAPBgNVBAgMCE5l
        dyBZb3JrMREwDwYDVQQHDAhOZXcgWW9yazETMBEGA1UECgwKT2xhcGljIElOQzEd
        MBsGA1UEAwwUKi5sb2NhbC5waG90b3JhbmsubWUxIDAeBgkqhkiG9w0BCQEWEWRl
        dm9wc0BvbGFwaWMuY29tMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA
        vL0RwEgRtHLC9A+JsTCN53ASwKmURB8u4Sw2D5qpFq9PXOrcY17XKIc3O+3Yjx78
        ecGfQ6JhuL0No3SsRWyrjz27IXP+otjASmUhSeSx3cIRtrlCFZnp0uXo26Pqxr1R
        FxjsxA6AezxLWq3MFHq59401rBD/l+pE8Yg2XfwIeSP20YqUclGMRYi54iOF21tk
        6QcME5kvf0e+BIwieW2uDTo8vexcbJw+UpQUjmzIhtATobMxAMgObWKSeY8BqVyH
        cP3brMzuXIVkveh7pg9UeBUqQfAy5IDkxSGDnSC+cYTdDEXW27bPJevgOXBbs7vP
        JM79MfGqwjQ+pgzY95ZNVwIDAQABo4G9MIG6MB0GA1UdDgQWBBTzLPi28mqyWsFK
        Fcof8E3Xiu7uiTAfBgNVHSMEGDAWgBTzLPi28mqyWsFKFcof8E3Xiu7uiTAMBgNV
        HRMEBTADAQH/MAsGA1UdDwQEAwIFoDBdBgNVHREEVjBUghJsb2NhbC5waG90b3Jh
        bmsubWWCFHdpZGdldHMucGhvdG9yYW5rLm1lghJkZWJ1Zy5waG90b3JhbmsubWWC
        FCoubG9jYWwucGhvdG9yYW5rLm1lMA0GCSqGSIb3DQEBBQUAA4IBAQBJkaR4zeSF
        KAokvtYuGS175sOoNj4zkcCTYzYV9AuX1GWj0qBoPk2t/m31g9DreO2CsOXNVcBT
        YFR+L+gAiSCX5VGgPfqb7TsfOpR2brHZL+Wh/HkZ4Y9vt0/196eMqFp7saPe/V65
        J9RBIU1CVnacINRaHokMX/1Qif88AtPg8gO+MOt47udSoD80ub7wtQlpMTCCzHK1
        gHodoC9ljZ5XVQzWlD+t6kuX4NjRotgBiYfAAu4Us3XeAyfPkQxoQNlixOi8LAby
        UCFU4i0vih7bJOqZL7fJxuHDw+hPXG2j/0lkKzmjuvw9JXtREssze/BD5DsaXe02
        bkhNTDqthPON
        -----END CERTIFICATE-----
      insecureEdgeTerminationPolicy: Redirect
      key: |-
        -----BEGIN RSA PRIVATE KEY-----
        MIIEpAIBAAKCAQEAvL0RwEgRtHLC9A+JsTCN53ASwKmURB8u4Sw2D5qpFq9PXOrc
        Y17XKIc3O+3Yjx78ecGfQ6JhuL0No3SsRWyrjz27IXP+otjASmUhSeSx3cIRtrlC
        FZnp0uXo26Pqxr1RFxjsxA6AezxLWq3MFHq59401rBD/l+pE8Yg2XfwIeSP20YqU
        clGMRYi54iOF21tk6QcME5kvf0e+BIwieW2uDTo8vexcbJw+UpQUjmzIhtATobMx
        AMgObWKSeY8BqVyHcP3brMzuXIVkveh7pg9UeBUqQfAy5IDkxSGDnSC+cYTdDEXW
        27bPJevgOXBbs7vPJM79MfGqwjQ+pgzY95ZNVwIDAQABAoIBAQCefb78UwjbGUvx
        G2MrMnTXltuIgl8JXY5GdJPpQp0feZQRmP/9SlUvqWyOnMqwVPr7W8bcSu347nkX
        fBB2NC1VGiecjgWUxqOjVY1AuhVK/X9Wi/ecoCUkfwCuANZUkgIYfUvFz8/ArP8y
        ZKPtxqmH4kLh/VxFO+stUI8nGVAcOM+3Rqc746RG+4mq8ff0t5mkSwKfMKxBcbO+
        U1nlsCjzWTg74yiCE5xPPD7jozC44gGO5czd54QaMVvl2hsj71V8YP8HLbaf+/mE
        OXIhaU5jn0/DSrsUeFJdVV1eLXd9rVGhgifdk5W2AB7waqrdZ+5BqPNOl8Z59wcg
        71F7SesxAoGBAOVcsmzAemJonIUbl8yfIYuqpit1a+XXX9ow5T0goezNT85Keuos
        BHfK6Si7UXyDChWEZUbELR22EX3Fj+RU/0TlYMpnypeLsXx61e2Led/yXbx8owLO
        AYg5bupqCI4QM70nHH5rvfb3uxUXGzb6Y+aiUE3yZul/njSzosNNla9jAoGBANKo
        kbeT3s9ilanYt4dgHs1YXnHqoC/BPS/OmFqOB4Q9m5QKZIWpouaHja4ifd04jqK9
        /p+r/goY0XdvDwvsPTZvCm5Ufulo7N7WOAvAMfdXcW7uSiv9I665RERRa2PqUssJ
        Ge7H1dk+MXC7Jq02hCDq9Nng1DfqheIXcuu9is59AoGBAJF9r6DUp81s1nyI+E3Q
        U5Mo+KdwoLT3XdImWgPgg1aXFhyhmj6ZFWx3xlcUG6iD5w2nIic1ofjK2WWSwKfy
        Usr9Rdye4iAneLqhoLpCU1j/gP5jgXPyAX7MD9Oa1zpmhKtj9+sppSLYGlBSi+zg
        ACb4p0AKl8VeMpjzqjeBK4ZJAoGAIVlMUDqZkE00EkJbs5O07J8rvG7/UvANhq73
        EYbgi7/RDFuk1EApqMMW29VcBZR5iCv5zj9FJUYOixDK2gFZI2/qv9KikMLqlNBm
        6P1RK63tKDmTBmm5p2Ru+T3GeXfUCY50S4fZQ94Dp6wJEGzL+AYaIw/jqMJ41XUO
        3WERQ2UCgYAZWObD+BxHlKBc2Q+KSDwG587BqL+tFnGwT91uJbGXBo/TgbW1Oftw
        f3eeGZ2PrX9ovzq9WvXzOdkVohaQuBQTi0hE167KXbxuFGAPiMKCDc1JspPVK6/8
        c/JGPaZUPEUKI0fqYDD1baxjqSc/9kzzRRs/JTXid8rMr2uSze4Zjw==
        -----END RSA PRIVATE KEY-----
      termination: edge
    to:
      kind: Service
      name: nodejs-content-engine-admin
      weight: 100
    wildcardPolicy: None
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: null
    labels:
      app: olapic-app-nodejs
      project: content-engine-admin-localbox
      service: nodejs
      vendor: Olapic
    name: nodejs-content-engine-admin
  spec:
    ports:
    - name: nodejs-content-engine-admin-endpoint
      port: 8080
      protocol: TCP
      targetPort: 8080
    - name: nodejs-content-engine-admin-test-endpoint
      port: 8081
      protocol: TCP
      targetPort: 8081
    selector:
      context: nodejs-content-engine-admin-context
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
kind: List
metadata: {}
