#!/bin/bash -e
files=$(git status -s | grep -E '[AM?]+\s.+?\.(scss|css)$' | cut -c3-)

# Prevent stylelint help message if no files matched
if [[ $files = "" ]] ; then
  exit 0
fi

stylelint ${files}
